# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f562a1e5ac9536c594ab6d52360b207b5259d6864a58e6578cfe27808de481daa41f9ef706cfeff2551ebfee0fcab4766b4fffdf2b2df718a6796525c18dc3

test:
  secret_key_base: ded1fe3c96e1671f29f2066b6604c9af4f0cc58531129fde07f2d86102e129a9e6ca0caf1b48e9c699bd09d839d2caeb80c54bc1213592e2e07edc808255ad09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
